### ISSUE TITLE
Incompatible game "Wanted"

### ISSUE THREAD

**Issue by negativeExponent** [gameblabla/sms_sdl#11]
When loading the game "Wanted", it only loads into a red screen (sometimes crashes on libretro port)

original report here: https://github.com/libretro/smsplus-gx/issues/32
since the tracelog appears sound-related, i've tried both maxim and crab sound modules but still the same issue.

```Wanted (USA, Europe, Brazil).zip' 
SMS Plus GX 1.8
CRC : 5359762D
sms.display 0, PAL is 1

**Comment by gameblabla** [comment]
This game will not work if an FM sound unit is plugged in.
It seems that this was not documented anywhere else besides a few other games having issues with it such as Great Baseball (1985), Pit Pot (Japan) and Teddy Boy Blues (Japan).

Note that the game requires the lightgun and this isn't implemented on the frontend side of things in SMS Plus GX currently.
(but it could be done on the libretro core)

Fixed as of https://github.com/gameblabla/sms_sdl/commit/ca69b71907337c96674d78254a782c0c6088304b
